# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Components
      autoload :ApiResponse, 'open_api_sdk/models/components/apiresponse.rb'
      autoload :Category, 'open_api_sdk/models/components/category.rb'
      autoload :Order, 'open_api_sdk/models/components/order.rb'
      autoload :OrderStatus, 'open_api_sdk/models/components/order_status.rb'
      autoload :Pet, 'open_api_sdk/models/components/pet.rb'
      autoload :PetInput, 'open_api_sdk/models/components/pet_input.rb'
      autoload :PetStatus, 'open_api_sdk/models/components/pet_status.rb'
      autoload :Security, 'open_api_sdk/models/components/security.rb'
      autoload :Tag, 'open_api_sdk/models/components/tag.rb'
      autoload :User, 'open_api_sdk/models/components/user.rb'
    end
  end
end
