# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Errors
      autoload :APIError, 'open_api_sdk/models/errors/apierror.rb'
    end
  end
end
