# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true

module OpenApiSDK
  module Models
    module Operations
      autoload :AddPetRawResponse, 'open_api_sdk/models/operations/addpet_raw_response.rb'
      autoload :AddPetResponse, 'open_api_sdk/models/operations/addpet_response.rb'
      autoload :CreateUserResponse, 'open_api_sdk/models/operations/createuser_response.rb'
      autoload :CreateUsersWithArrayInputResponse, 'open_api_sdk/models/operations/createuserswitharrayinput_response.rb'
      autoload :CreateUsersWithListInputResponse, 'open_api_sdk/models/operations/createuserswithlistinput_response.rb'
      autoload :DeleteOrderRequest, 'open_api_sdk/models/operations/deleteorder_request.rb'
      autoload :DeleteOrderResponse, 'open_api_sdk/models/operations/deleteorder_response.rb'
      autoload :DeletePetRequest, 'open_api_sdk/models/operations/deletepet_request.rb'
      autoload :DeletePetResponse, 'open_api_sdk/models/operations/deletepet_response.rb'
      autoload :DeleteUserRequest, 'open_api_sdk/models/operations/deleteuser_request.rb'
      autoload :DeleteUserResponse, 'open_api_sdk/models/operations/deleteuser_response.rb'
      autoload :File, 'open_api_sdk/models/operations/file.rb'
      autoload :FindPetsByStatusRequest, 'open_api_sdk/models/operations/findpetsbystatus_request.rb'
      autoload :FindPetsByStatusResponse, 'open_api_sdk/models/operations/findpetsbystatus_response.rb'
      autoload :FindPetsByTagsRequest, 'open_api_sdk/models/operations/findpetsbytags_request.rb'
      autoload :FindPetsByTagsResponse, 'open_api_sdk/models/operations/findpetsbytags_response.rb'
      autoload :GetInventorySecurity, 'open_api_sdk/models/operations/getinventory_security.rb'
      autoload :GetInventoryResponse, 'open_api_sdk/models/operations/getinventory_response.rb'
      autoload :GetOrderByIdRequest, 'open_api_sdk/models/operations/getorderbyid_request.rb'
      autoload :GetOrderByIdResponse, 'open_api_sdk/models/operations/getorderbyid_response.rb'
      autoload :GetPetByIdSecurity, 'open_api_sdk/models/operations/getpetbyid_security.rb'
      autoload :GetPetByIdRequest, 'open_api_sdk/models/operations/getpetbyid_request.rb'
      autoload :GetPetByIdResponse, 'open_api_sdk/models/operations/getpetbyid_response.rb'
      autoload :GetUserByNameRequest, 'open_api_sdk/models/operations/getuserbyname_request.rb'
      autoload :GetUserByNameResponse, 'open_api_sdk/models/operations/getuserbyname_response.rb'
      autoload :LoginUserRequest, 'open_api_sdk/models/operations/loginuser_request.rb'
      autoload :LoginUserResponse, 'open_api_sdk/models/operations/loginuser_response.rb'
      autoload :LogoutUserResponse, 'open_api_sdk/models/operations/logoutuser_response.rb'
      autoload :PlaceOrderResponse, 'open_api_sdk/models/operations/placeorder_response.rb'
      autoload :Status, 'open_api_sdk/models/operations/status.rb'
      autoload :UpdatePetWithFormRequestBody, 'open_api_sdk/models/operations/updatepetwithform_requestbody.rb'
      autoload :UpdatePetWithFormRequest, 'open_api_sdk/models/operations/updatepetwithform_request.rb'
      autoload :UpdatePetWithFormResponse, 'open_api_sdk/models/operations/updatepetwithform_response.rb'
      autoload :UpdatePetRawResponse, 'open_api_sdk/models/operations/updatepet_raw_response.rb'
      autoload :UpdatePetResponse, 'open_api_sdk/models/operations/updatepet_response.rb'
      autoload :UpdateUserRequest, 'open_api_sdk/models/operations/updateuser_request.rb'
      autoload :UpdateUserResponse, 'open_api_sdk/models/operations/updateuser_response.rb'
      autoload :UploadFileRequestBody, 'open_api_sdk/models/operations/uploadfile_requestbody.rb'
      autoload :UploadFileRequest, 'open_api_sdk/models/operations/uploadfile_request.rb'
      autoload :UploadFileResponse, 'open_api_sdk/models/operations/uploadfile_response.rb'
    end
  end
end
