# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true

module OpenApiSDK
  autoload :Openapi, 'open_api_sdk/openapi'
  autoload :Pet, 'open_api_sdk/pet'
  autoload :Store, 'open_api_sdk/store'
  autoload :User, 'open_api_sdk/user'
  module Models
    autoload :Components, 'open_api_sdk/models/components'
    autoload :Operations, 'open_api_sdk/models/operations'
    autoload :Errors, 'open_api_sdk/models/errors'
    autoload :Callbacks, 'open_api_sdk/models/callbacks'
  end
end

require_relative 'open_api_sdk/utils/utils'
require_relative 'open_api_sdk/utils/request_bodies'
require_relative 'open_api_sdk/utils/query_params'
require_relative 'open_api_sdk/utils/forms'
require_relative 'open_api_sdk/utils/headers'
require_relative 'open_api_sdk/utils/url'
require_relative 'open_api_sdk/utils/security'
require_relative 'crystalline'
require_relative 'open_api_sdk/sdkconfiguration'
