# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    
      # PetStatus - pet status in the store
      class PetStatus


        include ::Crystalline::Enum

        enums do
          AVAILABLE = new('available')
          PENDING = new('pending')
          SOLD = new('sold')
        end
      end
    end
  end
end
