# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Components
    

      class User
        
        include Crystalline::MetadataFields


        field :id, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }

        field :username, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('username') } }

        field :first_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('firstName') } }

        field :last_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('lastName') } }

        field :email, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('email') } }

        field :password, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('password') } }

        field :phone, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('phone') } }
        # User Status
        field :user_status, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('userStatus') } }

        
        def initialize(id: nil, username: nil, first_name: nil, last_name: nil, email: nil, password: nil, phone: nil, user_status: nil)
          @id = id
          @username = username
          @first_name = first_name
          @last_name = last_name
          @email = email
          @password = password
          @phone = phone
          @user_status = user_status
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @username == other.username
          return false unless @first_name == other.first_name
          return false unless @last_name == other.last_name
          return false unless @email == other.email
          return false unless @password == other.password
          return false unless @phone == other.phone
          return false unless @user_status == other.user_status
          true
        end
      end
    end
  end
end
