# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class DeleteOrderRequest
        
        include Crystalline::MetadataFields

        # ID of the order that needs to be deleted
        field :order_id, ::Integer, { 'path_param': { 'field_name': 'orderId', 'style': 'simple', 'explode': false } }

        
        def initialize(order_id:)
          @order_id = order_id
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @order_id == other.order_id
          true
        end
      end
    end
  end
end
