# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class DeletePetRequest
        
        include Crystalline::MetadataFields

        # Pet id to delete
        field :pet_id, ::Integer, { 'path_param': { 'field_name': 'petId', 'style': 'simple', 'explode': false } }

        field :api_key, Crystalline::Nilable.new(::String), { 'header': { 'field_name': 'api_key', 'style': 'simple', 'explode': false } }

        
        def initialize(pet_id:, api_key: nil)
          @pet_id = pet_id
          @api_key = api_key
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @pet_id == other.pet_id
          return false unless @api_key == other.api_key
          true
        end
      end
    end
  end
end
