# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class DeleteUserRequest
        
        include Crystalline::MetadataFields

        # The name that needs to be deleted
        field :username, ::String, { 'path_param': { 'field_name': 'username', 'style': 'simple', 'explode': false } }

        
        def initialize(username:)
          @username = username
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @username == other.username
          true
        end
      end
    end
  end
end
