# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class FindPetsByTagsRequest
        
        include Crystalline::MetadataFields

        # Tags to filter by
        field :tags, Crystalline::Array.new(::String), { 'query_param': { 'field_name': 'tags', 'style': 'form', 'explode': true } }

        
        def initialize(tags:)
          @tags = tags
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @tags == other.tags
          true
        end
      end
    end
  end
end
