# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class GetPetByIdRequest
        
        include Crystalline::MetadataFields

        # ID of pet to return
        field :pet_id, ::Integer, { 'path_param': { 'field_name': 'petId', 'style': 'simple', 'explode': false } }

        
        def initialize(pet_id:)
          @pet_id = pet_id
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @pet_id == other.pet_id
          true
        end
      end
    end
  end
end
