# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class LoginUserRequest
        
        include Crystalline::MetadataFields

        # The user name for login
        field :username, ::String, { 'query_param': { 'field_name': 'username', 'style': 'form', 'explode': true } }
        # The password for login in clear text
        field :password, ::String, { 'query_param': { 'field_name': 'password', 'style': 'form', 'explode': true } }

        
        def initialize(username:, password:)
          @username = username
          @password = password
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @username == other.username
          return false unless @password == other.password
          true
        end
      end
    end
  end
end
