# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class UpdatePetWithFormRequestBody
        
        include Crystalline::MetadataFields

        # Updated name of the pet
        field :name, Crystalline::Nilable.new(::String), { 'form': { 'field_name': 'name' } }
        # Updated status of the pet
        field :status, Crystalline::Nilable.new(::String), { 'form': { 'field_name': 'status' } }

        
        def initialize(name: nil, status: nil)
          @name = name
          @status = status
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @name == other.name
          return false unless @status == other.status
          true
        end
      end
    end
  end
end
