# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class UpdateUserRequest
        
        include Crystalline::MetadataFields

        # name that need to be updated
        field :username, ::String, { 'path_param': { 'field_name': 'username', 'style': 'simple', 'explode': false } }
        # Updated user object
        field :user, Models::Components::User, { 'request': { 'media_type': 'application/json' } }

        
        def initialize(username:, user:)
          @username = username
          @user = user
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @username == other.username
          return false unless @user == other.user
          true
        end
      end
    end
  end
end
