# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: false
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class UploadFileRequest
        
        include Crystalline::MetadataFields

        # ID of pet to update
        field :pet_id, ::Integer, { 'path_param': { 'field_name': 'petId', 'style': 'simple', 'explode': false } }

        field :request_body, Crystalline::Nilable.new(Models::Operations::UploadFileRequestBody), { 'request': { 'media_type': 'multipart/form-data' } }

        
        def initialize(pet_id:, request_body: nil)
          @pet_id = pet_id
          @request_body = request_body
        end

        
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @pet_id == other.pet_id
          return false unless @request_body == other.request_body
          true
        end
      end
    end
  end
end
